---
- name: AWX 템플릿 배포
  hosts: genie_vm
  vars:
    base_path: 'genie'
    genie_ip: 'localhost'
  gather_facts: no
  tasks:

  - name: AWX 초기 관리자 패스워드 추출
    shell: kubectl get -n awx secret awx-admin-password -o jsonpath="{.data.password}" | base64 --decode
    register: admin_password

  # Wordpress
  - name: Create wordpress deploy playbook
    awx.awx.job_template:
      name: 워드프레스 - 배포
      description: 워드프레스 배포
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: wordpress/wordpress_deploy.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"
      extra_vars: 
        instance_temp: "CentOS-8-cloudinit"
        instance_computeoffer: "2C-4GB-RBD"

  - name: Create wordpress state check playbook
    awx.awx.job_template:
      name: 워드프레스 - 상태체크
      description: 워드프레스 상태체크
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: wordpress/wordpress_check.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"

  - name: Create wordpress delete playbook
    awx.awx.job_template:
      name: 워드프레스 - 삭제
      description: 워드프레스 삭제
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: wordpress/wordpress_destroy.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"
      
  # Nextcloud
  # - name: Generate random string with length 5
  #   debug:
  #     var: lookup('community.general.random_string', length=5)

  - name: Create nextcloud deploy playbook
    awx.awx.job_template:
      name: 넥스트클라우드 - 배포
      description: 넥스트클라우드 배포
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: nextcloud/nextcloud_deploy.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"
      extra_vars: 
        uuid: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=5') }}"
        instance_name: "nextcloud-deploy-vm"
        instance_temp: "CentOS-8-cloudinit"
        instance_computeoffer: "2C-4GB-RBD"

  # - name: Create nextcloud state check playbook
  #   awx.awx.job_template:
  #     name: 넥스트클라우드 - 상태체크
  #     description: 넥스트클라우드 상태체크
  #     job_type: "run"
  #     inventory: genie_inventory
  #     project: playbook_project
  #     playbook: nextcloud/nextcloud_check.yml
  #     credentials:
  #       - "automation_controller_credential"
  #     state: "present"
  #     controller_host: "http://{{ genie_ip }}:80"
  #     controller_username: admin
  #     controller_password: "{{ admin_password.stdout }}"

  # - name: Create nextcloud delete playbook
  #   awx.awx.job_template:
  #     name: 넥스트클라우드 - 삭제
  #     description: 넥스트클라우드 삭제
  #     job_type: "run"
  #     inventory: genie_inventory
  #     project: playbook_project
  #     playbook: nextcloud/nextcloud_destroy.yml
  #     credentials:
  #       - "automation_controller_credential"
  #     state: "present"
  #     controller_host: "http://{{ genie_ip }}:80"
  #     controller_username: admin
  #     controller_password: "{{ admin_password.stdout }}"

  # 3Tier
  - name: Create 3tier deploy playbook
    awx.awx.job_template:
      name: 전자정부프레임워크 웹 - 배포
      description: 전자정부프레임워크 웹 배포
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: 3tier/tier_deploy.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"
      extra_vars: 
        instance_temp: "CentOS-8-cloudinit"
        instance_computeoffer: "2C-4GB-RBD"

  - name: Create 3tier state check playbook
    awx.awx.job_template:
      name: 전자정부프레임워크 웹 - 상태체크
      description: 전자정부프레임워크 웹 상태체크
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: 3tier/tier_check.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"

  - name: Create 3tier delete playbook
    awx.awx.job_template:
      name: 전자정부프레임워크 웹 - 삭제
      description: 전자정부프레임워크 웹 삭제
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: 3tier/tier_destroy.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"    