---
- name: State Httpd
  hosts: localhost
  gather_facts: no
  tasks:
##### Deploy VirtualMachine #####

    - name: 배포한 가상머신 정보 수집
      cs_instance_info:
        api_url: "{{ lookup('env', 'MOLD_API_URL') }}"
        api_key: "{{ lookup('env', 'MOLD_API_KEY') }}"
        api_secret: "{{ lookup('env', 'MOLD_SECRET_KEY') }}"
        name: nextcloud-deploy-vm
      delegate_to: localhost
      register: vm

    - name: 배포 가상머신 ip 정보 수집
      debug:
        msg: "{{ vm.instances[0].nic[0].ipaddress }}"

    - name: 배포 가상머신 인메모리 inventory에 등록
      add_host:
        hostname: "{{ vm.instances[0].nic[0].ipaddress }}"
        groups:
          - deployVmIp

##### State Httpd #####
- name: "State Httpd"
  hosts: deployVmIp
  gather_facts: no
  vars:
    - service: httpd.service
  tasks:
    - name: populate service facts
      ansible.builtin.service_facts:
    - debug: var=services[service]['status']
    - debug:
        msg: "{{ services[service]['status'] }}"

    - name: register resource
      ansible.builtin.command: python /root/test_sj/cs_api.py \
	-c listAutomationDeployedResource \
	-ip 10.10.3.10 \
	-ak FLdq0Y9F74VlAGPIHx2w6etYfj28pOJeDl1ICOtBWTj5U_GPfVMlBMwbxswMp5Gk8v-BeaQnT0tVX5SjMI9_zA \
	-sk hyvHQv5y10qBu_NHwlL3BuOTGUciSsWg-qSa-R_CPWJYpFP8Knck5o-3RCSXSou7uPx3d9x4gFOSH8C6-WYk6g \
	-n ServiceName2
    



    # - debug: var=services_state.ansible_facts.services["httpd.service"].state
    # - debug: var=services_state.ansible_facts.services["mysqld.service"].state