---
- name: State Httpd
  hosts: localhost
  gather_facts: no
  tasks:
##### Deploy VirtualMachine #####

    - name: 배포한 가상머신 정보 수집
      cs_instance_info:
        api_url: "{{ lookup('env', 'MOLD_API_URL') }}"
        api_key: "{{ lookup('env', 'MOLD_API_KEY') }}"
        api_secret: "{{ lookup('env', 'MOLD_SECRET_KEY') }}"
        name: nextcloud-deploy-vm
      delegate_to: localhost
      register: vm

    - name: 배포 가상머신 ip 정보 수집
      debug:
        msg: "{{ vm.instances[0].nic[0].ipaddress }}"

    - name: 배포 가상머신 인메모리 inventory에 등록
      add_host:
        hostname: "{{ vm.instances[0].nic[0].ipaddress }}"
        groups:
          - deployVmIp

##### State Httpd #####
- name: "State Httpd"
  hosts: deployVmIp
  gather_facts: no
  tasks:
    - name: populate service facts
      ansible.builtin.service_facts:
      register: services_state
    - debug: var=services_state.ansible_facts.services["httpd.service"].state
      register:result
    - debug: var=result
    # - debug: var=services_state.ansible_facts.services["mysqld.service"].state