---
- name: State Httpd
  hosts: localhost
  gather_facts: no
  tasks:
##### Deploy VirtualMachine #####

    - name: 배포한 가상머신 정보 수집
      cs_instance_info:
        api_url: "{{ lookup('env', 'MOLD_API_URL') }}"
        api_key: "{{ lookup('env', 'MOLD_API_KEY') }}"
        api_secret: "{{ lookup('env', 'MOLD_SECRET_KEY') }}"
        name: nextcloud-deploy-vm
      delegate_to: localhost
      register: vm

    - name: 배포 가상머신 ip 정보 수집
      debug:
        msg: "{{ vm.instances[0].nic[0].ipaddress }}"

    - name: 배포 가상머신 인메모리 inventory에 등록
      add_host:
        hostname: "{{ vm.instances[0].nic[0].ipaddress }}"
        groups:
          - deployVmIp
    
##### State Httpd #####
- name: "State Httpd"
  hosts: deployVmIp
  gather_facts: no
  vars:
    - service: httpd.service
  tasks:
    - name: populate service facts
      ansible.builtin.service_facts:
    - debug: var=services[service]['status']
    - debug:
        msg: "{{ services[service]['status'] }}"
    - name: debug set fact
      set_fact:
        http_status: "{{ services[service]['status'] }}"

##### Save State Httpd #####
- name: "Save State Httpd"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: register resource
      ansible.builtin.command: python2 /home/runner/mold_genie_api.py \
        -c listAutomationDeployedResource \
        -ip 10.10.254.168 \
        -ak ArfB-Y2r8LXfeWBmyNzpCgk1aOzg2s_O8PYXLX6uNRKg7lOWyd16nTshg4fsmEWs0dnEk8PIb0do0eczlysFpg \
        -sk g8Cghfff4Fc-n_iEYoHDJxnIv6sB0wJFx1CwtgEvBwJZw-W41Dblg7FA-oWN_EfO_C__f90STJDOPwlx3ftkUg \
        -n Nextcloud
      register: list
      
    - name: debug list stdout
      set_fact:
        list_jsondata: "{{ list.stdout | from_json }}"
    - debug:
        var: list_jsondata
    - name: debug list stdout2
      debug:
        msg: "{{ list_jsondata.listautomationdeployedresourceresponse.automationdeployedresource[0].id }}"

    - name: debug http status
      debug:
        msg: "{{ http_status }}"


    - name: register resource
      ansible.builtin.command: python2 /home/runner/mold_genie_api.py \
        -c addDeployedUnitResource \
        -ip 10.10.254.168 \
        -ak ArfB-Y2r8LXfeWBmyNzpCgk1aOzg2s_O8PYXLX6uNRKg7lOWyd16nTshg4fsmEWs0dnEk8PIb0do0eczlysFpg \
        -sk g8Cghfff4Fc-n_iEYoHDJxnIv6sB0wJFx1CwtgEvBwJZw-W41Dblg7FA-oWN_EfO_C__f90STJDOPwlx3ftkUg \
        -gid {{ list_jsondata.listautomationdeployedresourceresponse.automationdeployedresource[0].id }} \
        -vid 98fb8532-c4fe-432c-a301-d5d60936ad22 \
        -un httpd2 \
        -s {{ services[service]['status'] }}

    #     #.listautomationdeployedresourceresponse.automationdeployedresource[0].name
    # - name: debug list stdout_lines
    #   debug:
    #     msg: "{{ list.stdout_lines }}"


    # - debug: var=services_state.ansible_facts.services["httpd.service"].state
    # - debug: var=services_state.ansible_facts.services["mysqld.service"].state