---
- name: State Httpd
  hosts: 10.10.3.35
  gather_facts: no
  tasks:
##### Deploy VirtualMachine #####

    - name: register resource
      ansible.builtin.command: "touch /home/runner/test123.sh"

    # - debug: var=services_state.ansible_facts.services["httpd.service"].state
    # - debug: var=services_state.ansible_facts.services["mysqld.service"].state