---
### Deploy DB VirtualMachine ###
- name: Genie를 활용한 Mold VM 배포(DB Server)
  hosts: localhost
  vars:
    db_instance_nm: "tier-db-deploy-vm2"
  gather_facts: no
  tasks:

    - name: Include task list in play
      ansible.builtin.include_tasks: tier_test2.yml

### Deploy DB Server ###
- name: Deploy DB Server
  hosts: db_deployVmIp
  gather_facts: no
  vars:
    db_port: "3306"
    db_protocol: "tcp"

    # MySQL Settings
    mysql_root_password: Ablecloud1!
    mysql_db: cloud
  tasks:

    - name: Include task list in play
      ansible.builtin.include_tasks: tier_test3.yml