---
### Deploy DB VirtualMachine ###
- name: Genie를 활용한 Mold VM 배포(DB Server)
  hosts: localhost
  vars:
    db_instance_nm: "tier-db-deploy-vm2"
  gather_facts: no
  tasks:

    - name: Include task list in play
      ansible.builtin.include_tasks: tier_test2.yml
